/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cell;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import com.form.FormHome;

/**
 *
 * @author Administrator
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }

    public void initEvent(TableActionEvent event, int row) {

        cmdrefuse.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.Onrefuse(row); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

        });

        cmdApprove.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.Onapprove(row); // Modified to call Onapprove
            }
        });
        
        Cmddownload.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.Ondownload(row); // Modified to call Onapprove
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionButton1 = new com.cell.ActionButton();
        Cmddownload = new com.cell.ActionButton();
        cmdApprove = new com.cell.ActionButton();
        cmdrefuse = new com.cell.ActionButton();

        Cmddownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/10.png"))); // NOI18N
        Cmddownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmddownloadActionPerformed(evt);
            }
        });

        cmdApprove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/11.png"))); // NOI18N
        cmdApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdApproveActionPerformed(evt);
            }
        });

        cmdrefuse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/12.png"))); // NOI18N
        cmdrefuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdrefuseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cmddownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdrefuse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdApprove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmdrefuse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(Cmddownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CmddownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmddownloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmddownloadActionPerformed

    private void cmdApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdApproveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdApproveActionPerformed

    private void cmdrefuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdrefuseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdrefuseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.cell.ActionButton Cmddownload;
    private com.cell.ActionButton actionButton1;
    private com.cell.ActionButton cmdApprove;
    private com.cell.ActionButton cmdrefuse;
    // End of variables declaration//GEN-END:variables
}
